version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    user: root
    container_name: MsSqlServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - ./DB:/var/opt/mssql/data
    